import Head from "next/head";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import vector from "@/public/vector.svg";
import { NavDesktop } from "@/components";

const { src: vec } = vector;

const Home = () => {
  const [loader, setLoader] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setLoader(false);
    }, 2000);
  }, []);
  return (
    <>
      <Head>
        <title>itNova</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loader && (
        <motion.div
          className="loader"
          initial={{ opacity: 1 }}
          whileInView={{ opacity: 0 }}
        ></motion.div>
      )}
      <main className="home__container">
        <NavDesktop />
        <img src={vec} alt="vector" className="vector" />
        <header className="home__header">
          <section className="header__section">
            <motion.h1
              initial={{ opacity: 0, y: "2rem" }}
              whileInView={{
                y: 0,
                opacity: 1,
                transition: { duration: 1, ease: "easeInOut", delay: 1.2 },
              }}
              className="home__title"
            >
              itNova
            </motion.h1>
            <motion.h2
              initial={{ opacity: 0, y: "2rem" }}
              whileInView={{
                y: 0,
                opacity: 1,
                transition: {
                  duration: 1,
                  ease: "easeInOut",
                  delay: 1.4,
                },
              }}
              className="home__subtitle"
            >
              The unified Moroccan
              <br />
              IT Platform
            </motion.h2>
          </section>
          <motion.button
            className="home__cta"
            initial={{
              border: "1.5px solid transparent",
              backgroundColor: "rgba(255,255,255,1)",
              color: "#000000",
              opacity: 0,
              y: "2rem",
            }}
            whileInView={{
              y: 0,
              opacity: 1,
              transition: {
                duration: 1,
                ease: "easeInOut",
                delay: 1.6,
              },
            }}
            whileHover={{
              border: "1.5px solid #FFFFFF",
              backgroundColor: "rgba(0,0,0,0)",
              color: "#FFFFFF",
              transition: { duration: 0.3, ease: "easeInOut" },
            }}
          >
            Discover
          </motion.button>
        </header>
      </main>
    </>
  );
};

export default Home;
